---
name: Contract Addresses - Download

inputs:
  project:
    description: Name of the project
    required: true
  chain-environment:
    description: Chain environment
    required: true
  frontend-environment:
    description: Name of the frontend app environment
    required: true
  addresses:
    description: File that contains addresses
    required: true
  aws-access-key-id:
    description: AWS access key id
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true
  aws-region:
    description: AWS region
    required: true
  s3-bucket:
    description: Name of the S3 bucket
    required: true

runs:
  using: "composite"
  steps:
    - name: Download files from S3 AWS bucket
      shell: bash
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
      run: |
        s3_art_path="${{ inputs.project }}/addresses/${{ inputs.chain-environment }}"
        aws s3 cp s3://${{ secrets.CONTRACTS_S3BUCKET_NAME }}/${s3_art_path}/${{ inputs.frontend-environment }}.json .
