---
name: Contract Addresses - Download

inputs:
  project:
    description: Name of the project
    required: true
  chain-environment:
    description: Chain environment
    required: true
  frontend-environment:
    description: Name of the frontend app environment
    required: true
  dst-addresses:
    description: Path where addresses file should be saved
    required: true
  aws-access-key-id:
    description: AWS access key id
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true
  aws-region:
    description: AWS region
    required: true
  s3-bucket:
    description: Name of the S3 bucket
    required: true
  if-not-exist:
    description: Action to be taken when destination file does not exists, one of 'skip' or 'fallback'

runs:
  using: "composite"
  steps:
    - name: Download contract addresses from AWS S3 bucket
      uses: Cardinal-Cryptography/github-actions/get-file-from-s3@v6
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
      with:
        destination-path: ${{ inputs.dst-addresses }}
        s3-bucket-path: ${{ inputs.project }}/addresses/${{ inputs.chain-environment }}/${{ inputs.frontend-environment }}.json
        s3-bucket-name: ${{ inputs.s3-bucket }}
        if-not-exist: ${{ inputs.if-not-exist }}
