---
name: Get aleph-node system version
description: Queries Testnet or Mainnet RPC endpoint call system.version, and parses commit SHA
  from the response
inputs:
  env:
    required: true
    description: mainnet or testnet
outputs:
  sha:
    description: Commit SHA of RPC call system.version compatible with ECR (7 characters)
    value: ${{ steps.rpc-system-version.outputs.sha }}
  full-sha:
    description: Full commit SHA of RPC call system.version
    value: ${{ steps.rpc-system-version.outputs.full-sha }}

runs:
  using: composite
  steps:
    - name: Validate action inputs
      shell: bash
      run: |
        if [[ '${{ inputs.env }}' != 'testnet' && '${{ inputs.env }}' != 'mainnet' ]]; then
          echo "Error: inputs.env should be either mainnet or testnet!"
          exit 1
        fi

    - name: Checkout aleph-node repo with full depth
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Query RPC system.version
      id: rpc-system-version
      shell: bash
      # yamllint disable rule:line-length
      run: |
        COMMIT_ID=$(curl -s -H "Content-Type: application/json" \
          -d '{"id":1, "jsonrpc":"2.0", "method": "system_version"}' \
          '${{ inputs.env == 'mainnet' && 'https://rpc.azero.dev' || 'https://rpc.test.azero.dev' }}' \
          | jq -r '.result' | cut -d "-" -f 2)
        sha=$(echo ${COMMIT_ID} | head -c 7)
        echo "sha=${sha}" >> $GITHUB_OUTPUT
        full_sha=$(git rev-parse ${COMMIT_ID})
        echo "full-sha=${full_sha}" >> $GITHUB_OUTPUT
      # yamllint enable rule:line-length


