---
name: Get aleph-node system version
description: Queries Testnet or Mainnet RPC endpoint call system.version, and parses commit SHA
  from the response
inputs:
  env:
    required: true
    description: mainnet or testnet
outputs:
  ecr-sha:
    description: Commit SHA of RPC call system.version compatible with ECR (7 characters)
    value: ${{ steps.rpc-system-version.outputs.ecr-sha }}
  full-sha:
    description: Commit SHA of RPC call system.version (longer version than ECR)
    value: ${{ steps.rpc-system-version.outputs.full-sha }}

runs:
  using: composite
  steps:
    - name: Validate action inputs
      shell: bash
      run: |
        if [[ '${{ inputs.env }}' != 'testnet' && '${{ inputs.env }}' != 'mainnet' ]]; then
          echo "Error: inputs.env should be either mainnet or testnet!"
          exit 1
        fi

    - name: Query RPC system.version
      id: rpc-system-version
      shell: bash
      # yamllint disable rule:line-length
      run: |
        COMMIT_ID=$(curl -s -H "Content-Type: application/json" \
          -d '{"id":1, "jsonrpc":"2.0", "method": "system_version"}' \
          '${{ inputs.env == 'mainnet' && 'https://rpc.azero.dev' || 'https://rpc.test.azero.dev' }}' \
          | jq -r '.result' | cut -d "-" -f 2)
        ecr_sha=$(echo ${COMMIT_ID} | head -c 7)
        echo "ecr-sha=${ecr_sha}" >> $GITHUB_OUTPUT
        echo "full-sha=${COMMIT_ID}" >> $GITHUB_OUTPUT
      # yamllint enable rule:line-length
