---
name: GH Deployments and Environments
description: |
  Creates, updates and deletes GitHub Deployments and Environments
inputs:
  action:
    description: One of 'create-deployment'
    required: true
  env:
    description: Environment name
    required: true
  ref:
    description: Ref for deployment
    required: true
  token:
    description: GitHub token
    required: true
  owner:
    description: Owner
    required: true
  repo:
    description: Repo
    required: true
runs:
  using: composite
  steps:
    - name: Create deployment
      shell: bash
      run: |
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.token }}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ inputs.owner }}/${{ inputs.repo }}/deployments \
          -d '{"ref":"${{ inputs.ref }}","environment":"${{ inputs.env }}"}' > tmp-output.txt
        cat tmp-output.txt
        deployment_id=$(cat tmp-output.txt | jq '.id')
        if [[ -n "${deployment_id}" ]]; then
          echo "Got deployment id of ${deployment_id}"
        else
          echo "!!! Error creating deployment"
          exit 1
        fi
