---
name: Delete branchpreview
description: Deletes branchpreview

inputs:
  gh-ci-token:
    description: 'GH token to be used in the action'
    required: true
  repo-branchpreviews-name:
    description: 'Name of the repository containing branchpreview manifests'
    required: true
  repo-branchpreview-templates-name:
    description: 'Name of the repository containing branchpreview templates'
    required: true
  argo-host:
    description: 'ArgoCD host'
    required: true
  argo-sync-user-token:
    description: 'ArgoCD user token to be used in the action'
    required: true
  repository-name:
    description: 'Repository name'
    required: true
  branch-name:
    description: 'Branch name'
    required: true
  git-commit-author:
    description: 'Git commit author when pushing to branchpreviews repository'
    required: true
  git-commit-email:
    description: 'Git commit email when pushing to branchpreviews repository'
    required: true

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [[
          ! "${{ inputs.repository-name }}" =~ ^[a-zA-Z0-9-]+$
        ]]
        then
          echo "!!! Invalid repository name"
          exit 1
        fi

        if [[
          ! "${{ inputs.branch-name }}" =~ ^[a-zA-Z0-9/_-]+$
        ]]
        then
          echo "!!! Invalid branch name"
          exit 1
        fi

    - name: Checkout branchpreviews repo
      uses: actions/checkout@v3
      with:
        repository: Cardinal-Cryptography/${{ inputs.repo-branchpreviews-name }}
        token: ${{ inputs.gh-ci-token }}
        path: "${{ inputs.repo-branchpreviews-name }}"
        ref: main

    - name: Checkout branchpreview templates repo
      uses: actions/checkout@v3
      with:
        repository: Cardinal-Cryptography/${{ inputs.repo-branchpreview-templates-name }}
        token: ${{ inputs.gh-ci-token }}
        path: "${{ inputs.repo-branchpreview-templates-name }}"
        ref: compatibility

    - name: Destroy branchpreview
      shell: bash
      env:
        OPSSH_TARGETPATH: ${{ github.workspace }}/${{ inputs.repo-branchpreviews-name }}
      run: |
        cd "${{ inputs.repo-branchpreview-templates-name }}"
        ./Ops.sh delete-branchpreview \
          "${{ inputs.repository-name }}" \
          "${{ inputs.branch-name }}"

    - name: Commit deletion of the branchpreview
      uses: EndBug/add-and-commit@v9.1.1
      with:
        author_name: "${{ inputs.git-commit-author }}"
        author_email: "${{ inputs.git-commit-email }}"
        message: "Delete branchpreview ${{ inputs.repository-name }}:${{ inputs.branch-name }}"
        add: '["*.yaml","*.txt"]'
        cwd: "${{ inputs.repo-branchpreviews-name }}"

    # we need self-hosted runner only because of this step
    - name: Refresh Argo and wait for the deletion to be finished
      shell: bash
      env:
        OPSSH_TARGETPATH: ${{ github.workspace }}/${{ inputs.repo-branchpreviews-name }}
      run: |
        cd "${{ inputs.repo-branchpreview-templates-name }}"
        ./Ops.sh refresh-branchpreviews "${{ inputs.argo-host }}" \
          "${{ inputs.argo-sync-user-token }}"
