---
name: Contract Artifact - Download

inputs:
  project:
    description: Name of the project
    required: true
  version:
    description: Version of the artifacts, eg. 'v1.0.0' or commit SHA
    required: true
  contract:
    description: Name of the contract
    required: true
  dst-artifact:
    description: Path where contract artifact should be saved
    required: true
  aws-access-key-id:
    description: AWS access key id
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true
  aws-region:
    description: AWS region
    required: true
  s3-bucket:
    description: Name of the S3 bucket
    required: true
  if-not-exist:
    description: Action to be taken when destination file does not exists, one of 'skip' or 'fallback'
    required: false
    default: 'fallback'

runs:
  using: "composite"
  steps:
    - name: Download contract artifact from AWS S3 bucket
      uses: Cardinal-Cryptography/github-actions/get-file-from-s3@A0-4026-add-code-for-dealing-with-contracts
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
      with:
        destination-path: ${{ inputs.dst-artifact }}
        s3-bucket-path: ${{ inputs.project }}/artifacts/${{ inputs.version }}/${{ inputs.contract }}/
        s3-bucket-name: ${{ inputs.s3-bucket }}
        if-not-exist: ${{ inputs.if-not-exist }}
