---
name: Contract Artifact - Store

inputs:
  project:
    description: Name of the project
    required: true
  version:
    description: Version of the artifacts, eg. 'v1.0.0' or commit SHA
    required: true
  contract:
    description: Name of the contract
    required: true
  src-artifact:
    description: Path to artifact file to be stored
    required: true
  aws-access-key-id:
    description: AWS access key id
    required: true
  aws-secret-access-key:
    description: AWS secret access key
    required: true
  aws-region:
    description: AWS region
    required: true
  s3-bucket:
    description: Name of the S3 bucket
    required: true
  if-exist:
    description: Action to be taken when destination file already exists, one of 'skip', 'overwrite' or 'fallback'
    required: false
    default: 'skip'

runs:
  using: "composite"
  steps:
    - name: Store contract artifact on AWS S3 bucket
      uses: Cardinal-Cryptography/github-actions/copy-file-to-s3@v6
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        AWS_DEFAULT_REGION: ${{ inputs.aws-region }}
      with:
        compression: false
        source-path: ${{ inputs.src-artifact }}
        s3-bucket-filename: ''
        s3-bucket-path: ${{ inputs.project }}/artifacts/${{ inputs.version }}/${{ inputs.contract }}
        s3-bucket-name: ${{ inputs.s3-bucket }}
        if-exist: ${{ inputs.if-exist }}
