---
name: Check Pull Request title
description:
  Checks if PR matches given regexp

inputs:
  pr-title:
    description: "The title of Pull Request"
    required: true
  regexp:
    description: "Regexp to check"
    required: true

runs:
  using: composite
  steps:
    - name: Check Pull Request title
      shell: bash
      env:
        PR_TITLE: ${{ inputs.pr-title }}
        REGEXP: ${{ inputs.regexp }}
      run: |
        if ! echo '${{ env.PR_TITLE }}' | grep -Eq '${{ env.REGEXP }}'; then
          echo -e "The PR title \
              '${{ env.PR_TITLE }}' \
               does not match regexp '${{ env.REGEXP }}'"
          exit 1
        fi