---
name: Contract Artifact - Store

on:
  workflow_call:
    inputs:
      project:
        description: Name of the project
        type: string
        required: true
      version:
        description: Version of the artifacts, eg. 'v1.0.0' or commit SHA
        type: string
        required: true
      artifacts:
        description: JSON that is a list with objects having 'contract' and 'artifact'
        type: string
        required: true
      checkout:
        description: Checkout the code
        type: boolean
        required: false
        default: false
      checkout-ref:
        description: Ref to be used when checking out the code
        type: string
        required: false
        default: ''
      download-artifacts:
        description: Set
        type: string
        required: false
        default: ''

jobs:
  check-vars-and-secrets:
    name: Check vars and secrets
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

  store-contract-artifact:
    needs: [check-vars-and-secrets]
    name: Store contract artifact
    runs-on: [self-hosted, Linux, X64, small]
    strategy:
      matrix: ${{ fromJson(inputs.artifacts) }}
    steps:
      - name: Checkout repository
        if: ${{ inputs.checkout == true }}
        uses: actions/checkout@v4
        ref: '${{ inputs.checkout-ref }}'

      - name: Download artifacts
        if: ${{ inputs.download-artifacts != '' }}
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ inputs.download-artifacts }}
          path: downloaded-artifacts

      - name: Test matrix values
        shell: bash
        run: |
          find downloaded-artifacts
          echo "${{ matrix.artifact }} -> ${{ secrets.CONTRACTS_S3BUCKET_NAME }} / ${{ inputs.project }}/artifacts/${{ inputs.version }}/${{ matrix.contract }}"

      #- name: Copy files to S3 AWS bucket
      #  uses: Cardinal-Cryptography/github-actions/copy-file-to-s3@v1
      #  env:
      #    AWS_ACCESS_KEY_ID: ${{ secrets.CONTRACTS_MOST_ARTIFACTS_RW_AWS_ACCESS_KEY_ID }}
      #    AWS_SECRET_ACCESS_KEY: ${{ secrets.CONTRACTS_MOST_ARTIFACTS_RW_AWS_SECRET_ACCESS_KEY }}
      #    AWS_DEFAULT_REGION: ${{ secrets.CONTRACTS_S3BUCKET_REGION }}
      #  with:
      #    compression: false
      #    source-path: ${{ matrix.artifact }}
      #    s3-bucket-filename: ''
      #    s3-bucket-path: ${{ inputs.project }}/artifacts/${{ inputs.version }}/${{ matrix.contract }}
      #    s3-bucket-name: ${{ secrets.CONTRACTS_S3BUCKET_NAME }}
