---
name: FE - Create

on:
  workflow_call:
    inputs:
      featurenet-name:
        description: 'Name of the featurenet'
        required: true
        type: string
      aleph-node-image:
        description: "FQDN of aleph-node image"
        required: true
        type: string
      rolling-update-partition:
        description: |
          Number from 0 to N-1, where N is size of am existing featurenet.
          All aleph-node-validator-N with an ordinal N that is great than or equal to the partition
          will be updated. If not specified, all nodes will be updated.
        required: false
        default: '0'
        type: string
    outputs:
      ws-hostname:
        description: Hostname of the WS endpoint
        value: ${{ jobs.create-featurenet.outputs.ws-hostname }}

jobs:
  validate-inputs:
    name: Validate inputs
    runs-on: ubuntu-20.04
    steps:
      - name: Validate inputs
        shell: bash
        # yamllint disable rule:line-length
        run: |
          if [[ ! '${{ inputs.featurenet-name }}' =~ ^[a-z0-9][a-z0-9\-]{4,48}$ ]]
          then
            echo '!!! Invalid featurenet name'
            exit 1
          fi
          if [[ ! '${{ inputs.aleph-node-image }}' =~ ^[a-z0-9][a-z0-9\._:/\-]{1,52}$ ]]; then
            echo "!!! Invalid aleph-node image"
            exit 1
          fi
        # yamllint enable rule:line-length

  check-vars-and-secrets:
    needs: [validate-inputs]
    name: Check vars and secrets
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

  create-featurenet:
    needs: [check-vars-and-secrets]
    name: Create featurenet
    runs-on: [self-hosted, Linux, X64, small]
    outputs:
      deployment-id: ${{ steps.deployment.outputs.deployment_id }}
      ws-hostname: ${{ steps.create-featurenet.outputs.ws-hostname }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Start featurenet Deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.CI_GH_TOKEN }}
          env: ${{ inputs.featurenet-name }}
          override: true
          debug: true

      - name: Update featurenet with image tag
        uses: Cardinal-Cryptography/github-actions/update-featurenet@A0-4268
        id: create-featurenet
        with:
          gh-ci-user: ${{ secrets.CI_GH_USER }}
          gh-ci-token: ${{ secrets.CI_GH_TOKEN }}
          argo-sync-user-token: ${{ secrets.ARGO_SYNC_USER_TOKEN }}
          repo-featurenet-template-name: ${{ secrets.REPO_FEATURENET_TEMPLATE_NAME }}
          featurenet-name: ${{ inputs.featurenet-name }}
          featurenet-aleph-node-image: ${{ inputs.aleph-node-image }}
          rolling-update-partition: ${{ inputs.rolling-update-partition }}
          git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
          git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
          wait-for-finalized-heads: "true"

      - name: Finish featurenet Deployment
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.CI_GH_TOKEN }}
          status: ${{ job.status }}
          env: ${{ inputs.featurenet-name }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          # yamllint disable-line rule:line-length
          env_url: https://dev.azero.dev/?rpc=wss%3A%2F%2F${{ steps.create-featurenet.outputs.ws-hostname }}#/explorer
          debug: true
