---
name: FE - Create from branch

on:
  workflow_call:
    inputs:
      featurenet-name:
        description: 'Name of featurenet'
        type: string
        required: true
      expiration:
        description: 'Time after which featurenet will be removed'
        required: false
        type: string
        default: '48h'
      replicas:
        description: 'Number of replicas to start, from 0 to 50'
        required: false
        default: '5'
        type: string
      internal:
        description: 'Internal network, accessible from VPN only'
        required: false
        type: boolean
        default: false

jobs:
  validate-inputs:
    name: Validate inputs
    runs-on: ubuntu-20.04
    steps:
      - name: Validate inputs
        shell: bash
        # yamllint disable rule:line-length
        run: |
          if [[
          ! '${{ inputs.featurenet-name }}' =~ ^[a-z0-9][a-z0-9\-]{4,48}$
          ]]
          then
            echo '!!! Invalid featurenet name'
            exit 1
          fi
        # yamllint enable rule:line-length

  check-vars-and-secrets:
    name: Check vars and secrets
    needs: [validate-inputs]
    uses: ./.github/workflows/_check-vars-and-secrets.yml
    secrets: inherit

  create-featurenet:
    needs: [check-vars-and-secrets]
    name: Create featurenet based on the PR
    runs-on: [self-hosted, Linux, X64, small]
    outputs:
      deployment-id: ${{ steps.deployment.outputs.deployment_id }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Delete old featurenet app and data
        if: contains(github.event.pull_request.labels.*.name, 'state:created-featurenet')
        uses: Cardinal-Cryptography/github-actions/delete-featurenet@A0-3516-refactor-helper
        with:
          gh-ci-token: ${{ secrets.CI_GH_TOKEN }}
          aws-access-key-id: ${{ secrets.AWS_DEVNET_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEVNET_SECRET_ACCESS_KEY }}
          ecr-public-registry: ${{ vars.ECR_PUBLIC_REGISTRY }}
          argo-sync-user-token: ${{ secrets.ARGO_SYNC_USER_TOKEN }}
          repo-featurenets-name: ${{ secrets.REPO_OPS_FEATURENETS_NAME }}
          repo-featurenet-template-name: ${{ secrets.REPO_FEATURENET_TEMPLATE_NAME }}
          argo-host: ${{ secrets.ARGOCD_DEVNET_HOST }}
          featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
          featurenet-name: ${{ inputs.featurenet-name }}
          git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
          git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}

      - name: Start featurenet Deployment
        uses: bobheadxi/deployments@v1.1.0
        id: deployment
        with:
          step: start
          token: ${{ secrets.CI_GH_TOKEN }}
          env: ${{ inputs.featurenet-name }}
          ref: ${{ github.head_ref }}
          override: true

      - name: Create featurenet from scratch
        uses: Cardinal-Cryptography/github-actions/create-featurenet@A0-3516-refactor-helper
        id: create-featurenet
        with:
          gh-ci-token: ${{ secrets.CI_GH_TOKEN }}
          argo-sync-user-token: ${{ secrets.ARGO_SYNC_USER_TOKEN }}
          repo-featurenets-name: ${{ secrets.REPO_OPS_FEATURENETS_NAME }}
          repo-featurenet-template-name: ${{ secrets.REPO_FEATURENET_TEMPLATE_NAME }}
          argo-host: ${{ secrets.ARGOCD_DEVNET_HOST }}
          ecr-public-registry: ${{ vars.ECR_PUBLIC_REGISTRY }}
          featurenet-keys-s3bucket-name: ${{ secrets.FEATURENET_KEYS_S3BUCKET_NAME }}
          expiration: ${{ inputs.expiration }}
          replicas: ${{ inputs.replicas }}
          internal: ${{ inputs.internal && 'true' || 'false' }}
          featurenet-name: ${{ inputs.featurenet-name }}
          git-commit-author: ${{ secrets.AUTOCOMMIT_AUTHOR }}
          git-commit-email: ${{ secrets.AUTOCOMMIT_EMAIL }}
          wait-for-finalized-heads: "true"

      - name: Remove deleted label if present
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        if: contains(github.event.pull_request.labels.*.name, 'state:deleted-featurenet')
        with:
          labels: 'state:deleted-featurenet'
          github_token: ${{ secrets.CI_GH_TOKEN }}

      - name: Finish featurenet Deployment
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.CI_GH_TOKEN }}
          status: ${{ job.status }}
          env: ${{ inputs.featurenet-name }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          # yamllint disable-line rule:line-length
          env_url: https://dev.azero.dev/?rpc=wss%3A%2F%2F${{ steps.create-featurenet.outputs.ws-hostname }}#/explorer
          ref: ${{ github.head_ref }}

      - name: Remove deployment request label if exists
        if: contains(github.event.pull_request.labels.*.name, 'trigger:create-featurenet')
        uses: actions-ecosystem/action-remove-labels@v1.3.0
        with:
          labels: 'trigger:create-featurenet'
          github_token: ${{ secrets.CI_GH_TOKEN }}

      - name: Add label to mark that featurenet has been created
        if: github.event_name == 'pull_request'
        uses: actions-ecosystem/action-add-labels@v1.1.0
        with:
          labels: 'state:created-featurenet'
          github_token: ${{ secrets.CI_GH_TOKEN }}
