---
name: Tmp test contract artifact store

on:
  push:
    branches:
      - A0-4026-add-code-for-dealing-with-contracts

jobs:
  artifacts:
    name: Add artifacts
    runs-on: [self-hosted, Linux, X64, small]
    steps:
      - name: Create files
        shell: bash
        run: |
          touch art1-1.txt
          touch art1-2.txt
          touch art2-1.txt
          touch art2-2.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts1
          path: |
            art1-1.txt
            art1-2.txt
  
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts2
          path: |
            art2-1.txt
            art2-2.txt
  test:
    name: Test sub-workflow
    uses: ./.github/workflows/_contract-artifact-store.yml
    with:
      project: 'most'
      version: 'v1.0.0'
      artifacts: >-
        {
          "include":
          [
            {
              "contract": "eth_governance",
              "artifact": "downloaded-artifacts/eth/artifacts/contracts/Governance.sol/Governance.json"
            }
          ]
        }
      checkout: true
      checkout-ref: ''
      download-artifacts: artifacts*
